language: python
sudo: false
cache: pip
dist: xenial
install:
  - pip install coveralls>=1.1 tox
# command to run tests
script:
  - tox
after_success:
  coveralls
services:
  - redis-server
matrix:
  include:
   - env: TOXENV=py310
     python: '3.10.8'
deploy:
  provider: pypi
  user: __token__
  password: $password
  on:
    tags: true
